### ISSUE TITLE
npm version still lacks the comma

### ISSUE THREAD

**Issue by topfunky** [ecto/node-scp#7]
Could you push a new version to npm? 

It looks like you've fixed the missing comma here, but the incorrect version is still the latest on npm.

Thanks!

**Comment by darcy** [comment]
+1

Thanks!

**Comment by Termina1** [comment]
Still no comma

**Comment by deanmao** [comment]
hah yeah, I see the npm version is still missing the comma...  I guess I can just use the master branch instead

**Comment by AdamMagaluk** [comment]
+1

**Comment by ecto** [comment]
Hey guys, sorry I missed this. I just pushed to npm @ version 0.0.3 :)
